# Generated by Django 5.1.7 on 2025-08-07 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlimit',
            name='note',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='note',
        ),
        migrations.AddField(
            model_name='budgetlimit',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetlimit',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='budget_limits', to='MoNiapp.note'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='MoNiapp.note'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
    ]
