# Generated by Django 5.1.7 on 2025-08-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0004_budgetlimit_warning_threshold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('user', 'category', 'month')},
        ),
    ]
