# Generated by Django 5.1.7 on 2025-08-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0005_alter_budgetlimit_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
