# Generated by Django 5.1.7 on 2025-08-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0014_remove_budgetlimit_notes_budgetlimit_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('otp_type', models.CharField(choices=[('register', 'Register'), ('forgot_password', 'Forgot Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
