# Generated by Django 5.1.7 on 2025-09-12 10:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0015_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsLink',
            fields=[
            ],
            options={
                'verbose_name': 'System Statistics',
                'verbose_name_plural': 'System Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('MoNiapp.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
    ]
