# Generated by Django 5.1.7 on 2025-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0003_category_is_default_alter_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetlimit',
            name='warning_threshold',
            field=models.FloatField(default=100),
        ),
    ]
