# Generated by Django 5.1.7 on 2025-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNiapp', '0013_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlimit',
            name='notes',
        ),
        migrations.AddField(
            model_name='budgetlimit',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
